alter session set "_ORACLE_SCRIPT"=true;
-- Tablespaces
CREATE SMALLFILE TABLESPACE BET_ITM
    DATAFILE '/u02/app/oracle/oradata/ORCL/BET_ITM1.DBF' SIZE 512M, '/u02/app/oracle/oradata/ORCL/BET_ITM2.DBF' SIZE 512M
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE BIGFILE TABLESPACE BET_AUDITING
    DATAFILE '/u02/app/oracle/oradata/ORCL/BET_AUDITING.DBF' SIZE 2G
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE UNDO TABLESPACE UNDO_BET_ITM
    DATAFILE '/u02/app/oracle/oradata/ORCL/BET_ITM_UNDO.DBF' SIZE 500M;

ALTER SYSTEM SET UNDO_TABLESPACE = UNDO_BET_ITM;

-- Profiles

CREATE  PROFILE developer LIMIT
    SESSIONS_PER_USER 1
    CONNECT_TIME 60
    IDLE_TIME 30
    FAILED_LOGIN_ATTEMPTS 5
    PASSWORD_LIFE_TIME 90;
   

CREATE  PROFILE web_application LIMIT
    SESSIONS_PER_USER 5
    CONNECT_TIME UNLIMITED
    IDLE_TIME UNLIMITED
    FAILED_LOGIN_ATTEMPTS 2
    PASSWORD_LIFE_TIME 30;

CREATE  PROFILE dba_admin LIMIT
    SESSIONS_PER_USER 1
    CONNECT_TIME 30
    IDLE_TIME UNLIMITED
    FAILED_LOGIN_ATTEMPTS 2
    PASSWORD_LIFE_TIME 30;

CREATE  PROFILE analyst LIMIT
    SESSIONS_PER_USER 1
    CONNECT_TIME 30
    IDLE_TIME 5
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 30
    PASSWORD_GRACE_TIME 3;

CREATE  PROFILE support_iii LIMIT
    SESSIONS_PER_USER 1
    CONNECT_TIME 240
    IDLE_TIME 5
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 20
    PASSWORD_GRACE_TIME 5;

CREATE  PROFILE reporter LIMIT
    SESSIONS_PER_USER 1
    CONNECT_TIME 90
    IDLE_TIME 15
    FAILED_LOGIN_ATTEMPTS 4
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_GRACE_TIME 5;

CREATE  PROFILE auditor LIMIT
    SESSIONS_PER_USER 1
    CONNECT_TIME 90
    IDLE_TIME 15
    FAILED_LOGIN_ATTEMPTS 4
    PASSWORD_LIFE_TIME UNLIMITED
    PASSWORD_GRACE_TIME 5;

-- Users
CREATE USER developer_user
    IDENTIFIED BY developer
    PROFILE developer
    DEFAULT TABLESPACE BET_ITM;

CREATE USER web_user
    IDENTIFIED BY webpage
    PROFILE web_application
    DEFAULT TABLESPACE BET_ITM;

CREATE USER dba_user
    IDENTIFIED BY dba
    PROFILE dba_admin
    DEFAULT TABLESPACE BET_ITM;

CREATE USER analyst_user
    IDENTIFIED BY analyst
    PROFILE analyst
    DEFAULT TABLESPACE BET_ITM;

CREATE USER support_user
    IDENTIFIED BY support
    PROFILE support_iii
    DEFAULT TABLESPACE BET_ITM;

CREATE USER reporter_user
    IDENTIFIED BY reporter
    PROFILE reporter
    DEFAULT TABLESPACE BET_ITM;

CREATE USER auditor_user
    IDENTIFIED BY auditor
    PROFILE auditor
    DEFAULT TABLESPACE BET_ITM;

CREATE USER backup_dba
    IDENTIFIED BY dbabackup
    PROFILE dba_admin
    DEFAULT TABLESPACE BET_ITM;

CREATE USER backup_developer
    IDENTIFIED BY devbackup
    PROFILE developer
    DEFAULT TABLESPACE BET_ITM;

CREATE USER backup_web
    IDENTIFIED BY webbackup
    PROFILE web_application
    DEFAULT TABLESPACE BET_ITM;
   
GRANT CREATE SESSION TO 
	developer_user, 
	web_user, 
	dba_user, 
	analyst_user, 
	support_user, 
	reporter_user, 
	auditor_user, 
	backup_dba, 
	backup_developer, 
	backup_web;

-- Tables

CREATE TABLE COUNTRIES(
	ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	COUNTRY_NAME VARCHAR2(255) NOT NULL CONSTRAINT COUNTRIES_CHECK CHECK (COUNTRY_NAME IN 'COLOMBIA'),
	SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT COUNTRIES_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLED'))
	) 
	TABLESPACE BET_ITM;

CREATE TABLE PROVIDENCES(
	ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	PROVIDENCE_NAME VARCHAR2(100) NOT NULL,
	COUNTRY_ID NUMBER(22,0) NOT NULL REFERENCES COUNTRIES(ID),
	SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT PROVIDENCES_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLED')))
	TABLESPACE BET_ITM;

CREATE TABLE CITIES(
	ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	CITY_NAME VARCHAR2(50) NOT NULL,
	PROVIDENCE_ID NUMBER(22,0) NOT NULL REFERENCES PROVIDENCES(ID),
	SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT CITIES_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLED')))
	TABLESPACE BET_ITM;

CREATE TABLE DOCUMENTS(
	ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	DOCUMENT_TYPE VARCHAR2(100) NOT NULL CONSTRAINT DOCUMENTS_TYPES CHECK (DOCUMENT_TYPE IN ('CC')),
	DOCUMENT_NAME VARCHAR2(100) NOT NULL,
	EXPEDITION_CITY_ID NUMBER(22,0) NOT NULL REFERENCES COUNTRIES(ID),
	EXPEDITION_DATE DATE,
	SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT DOCUMENTS_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLED')))
	TABLESPACE BET_ITM;

CREATE TABLE PREFERENCES(
	ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	ACCEPTED_TERMS VARCHAR2(8) NOT NULL CONSTRAINT TERMS_CHECK CHECK (ACCEPTED_TERMS IN ('CHECKED', 'NOT CHECKED')),
	ACCEPTED_BULLETIN VARCHAR2(8) CONSTRAINT BULLETIN_CHECK CHECK (ACCEPTED_BULLETIN IN ('CHECKED', 'NOT CHECKED')),
	SPORT_BETS_EMAILS VARCHAR2(8) CONSTRAINT SPORTS_EMAILS_CHECK CHECK (SPORT_BETS_EMAILS IN ('CHECKED', 'NOT CHECKED')),
	SMS VARCHAR2(8) CONSTRAINT SMS_CHECK CHECK (SMS IN ('CHECKED', 'NOT CHECKED')),
	BROWSER_NOTIFICATIONS VARCHAR2(8) CONSTRAINT BROWSER_CHECK CHECK (BROWSER_NOTIFICATIONS IN ('CHECKED', 'NOT CHECKED')),
	BET_CHART_NOTIFICATION VARCHAR2(8) CONSTRAINT BET_CHART_TERMS CHECK (BET_CHART_NOTIFICATION IN ('CHECKED', 'NOT CHECKED')),
	SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT PREFERENCES_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLED')))
	TABLESPACE BET_ITM;

CREATE TABLE PROMO_CODES(
	ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	START_DATE DATE,
	END_DATE DATE,
	STATUS VARCHAR2(8) NOT NULL CONSTRAINT CODE_STATE CHECK (STATUS IN ('PENDIENTE', 'EN PROCESO', 'RECHAZADA', 'EXITOSO')),
	SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT PROMO_CODES_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLE')))
	TABLESPACE BET_ITM;

CREATE TABLE DEPOSIT_LIMITS(
	ID NUMBER (22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	DAILY_DEPOSIT_LIMIT NUMBER(22,0) CONSTRAINT DAILY_DEPOSIT_CHECK CHECK (DAILY_DEPOSIT_LIMIT > 0),
	DAILY_DEPOSIT_TIMESTAMP TIMESTAMP,
	DAILY_BET_LIMIT NUMBER(22,0) CONSTRAINT DAILY_BET_CHECK CHECK (DAILY_BET_LIMIT > 0),
	DAILY_BET_TIMESTAMP TIMESTAMP,
	WEEKLY_DEPOSIT_LIMIT NUMBER(22,0) CONSTRAINT WEEKLY_DEPOSIT_CHECK CHECK (WEEKLY_DEPOSIT_LIMIT > 0),
	WEEKLY_DEPOSIT_TIMESTAMP TIMESTAMP,
	WEEKLY_BET_LIMIT NUMBER(22,0) CONSTRAINT WEEKLY_BET_CHECK CHECK (WEEKLY_BET_LIMIT > 0),
	WEEKLY_BET_TIMESTAMP TIMESTAMP,
	MONTHLY_DEPOSIT_LIMIT NUMBER(22,0) CONSTRAINT MONTHLY_DEPOSIT_CHECK CHECK (MONTHLY_DEPOSIT_LIMIT > 0),
	MONTHLY_DEPOSIT_TIMESTAMP TIMESTAMP,
	MONTHLY_BET_LIMIT NUMBER(22,0) CONSTRAINT MONTHLY_BET_CHECK CHECK (MONTHLY_BET_LIMIT > 0),
	MONTHLY_BET_TIMESTAMP TIMESTAMP,
	SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT DEPOSIT_LIMITS_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLE')))
	TABLESPACE BET_ITM;

CREATE TABLE BET_USERS(	
	ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	USER_NAME VARCHAR2(255) NOT NULL,
	MIDDLE_NAME VARCHAR2(255),	
	LAST_NAME VARCHAR2(255) NOT NULL,	
	SECOND_LAST_NAME VARCHAR2(255),	
	DOCUMENT_ID NUMBER(22,0) NOT NULL REFERENCES DOCUMENTs(ID),	
	FORMALITY VARCHAR2(255) CONSTRAINT FORMALITIES CHECK (FORMALITY IN ('MR', 'MSS')),
	NATIONALITY_ID NUMBER(22,0) NOT NULL REFERENCES COUNTRIES(ID),
	BIRTHDATE DATE NOT NULL,	
	BIRTH_COUNTRY_ID  NUMBER(22,0) NOT NULL REFERENCES COUNTRIES(ID),
	BIRTH_PROVIDENCE_ID  NUMBER(22,0) NOT NULL REFERENCES PROVIDENCES(ID),	
	BIRTH_CITY_ID  NUMBER(22,0) NOT NULL REFERENCES CITIES(ID),	
	POSTAL_CODE VARCHAR(8),
	ADDRESS VARCHAR2(255) NOT NULL,	
	ADDRESS_DETAIL  VARCHAR2(255),	
	EMAIL  VARCHAR2(255) NOT NULL,	
	PHONE_COUNTRY_PREFIX VARCHAR2(5) NOT NULL,	
	CELLPHONE  VARCHAR2(255) NOT NULL,	
	USER_PASSWORD  VARCHAR2(255) NOT NULL,	
	PREFERENCE_ID NUMBER(22,0) NOT NULL REFERENCES PREFERENCES(ID),
	PROMO_CODE_ID NUMBER(22,0) REFERENCES PROMO_CODES(ID),
	DEPOSIT_LIMIT_ID NUMBER(22,0) REFERENCES DEPOSIT_LIMITS(ID),
	SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT USERS_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLED')))
	TABLESPACE BET_ITM;

CREATE TABLE MATCHES(
	ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	LOCAL_TEAM VARCHAR2(255) NOT NULL,
	VISITOR_TEAM VARCHAR2(255) NOT NULL,
	MATCH_DATE DATE NOT NULL,
	MATCH_TIME TIMESTAMP NOT NULL,
	STATUS VARCHAR2(15) NOT NULL CONSTRAINT MATCH_STATUS CHECK (STATUS IN ('PROGRAMADO', 'EN CURSO', 'FINALIZADO')),
	SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT MATCHES_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLED')))
	TABLESPACE BET_ITM;

CREATE TABLE BETS(
	ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	BET_STATE VARCHAR2(2),
	BET_TYPE VARCHAR2(2),
	MATCH_ID NUMBER(22,0) REFERENCES MATCHES(ID),
	BET_MULTIPLIER_1 varchar2(10),
	BET_MULTIPLIER_2 varchar2(10),
	BET_MULTIPLIER_3 varchar2(10),
	SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT MATCHES_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLED')))
	TABLESPACE BET_ITM;

CREATE TABLE BETS_DETAILS(
ID NUMBER NOT NULL GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
BET_ID NUMBER,
MATCH_ID NUMBER,
BET_OPTION  varchar2(255),
BET_MULTIPLIER varchar2(255),
BET_AMOUNT varchar2(255),
STATUS CONSTRAINT BET_DETAIL_STATE 
CHECK (STATUS IN ('ABIERTA', 'GANADA', 'PERDIDA', 'VENDIDA','CANCELADA', 'REENBOLSADA', 'INVALIDA', 'RECHAZADA', 'PERDIDO', 'PARTE-APROBADA')
SOFT_DELETION VARCHAR2(8) NOT NULL CONSTRAINT USERS_DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLED')))
	TABLESPACE BET_ITM;

CREATE TABLE Users_Bets(
	ID NUMBER(22,0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	USER_ID NUMBER(22,0) NOT NULL REFERENCES BET_USERS(ID),
	BET_DETAIL_ID NUMBER(22,0) NOT NULL REFERENCES BET,
	SOFT_DELETION VARCHAR2(100) NOT NULL CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED', 'ENABLED')))
	TABLESPACE BET_ITM;

CREATE TABLE DEPOSITS(
ID NUMBER GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
DEPOSIT_AMOUNT varchar2(255),
PAYMENT_METHOD_ID NUMBER,
DEPOSIT_DESCRIPTION varchar2(255),
PAYMENT_METODS_ID NUMBER,
STATUS CONSTRAINT DEPOSIT_STATE_STATE CHECK (STATUS IN ('PENDIENTE' 'EN PROCESO', 'RECHAZADA', 'EXITOSO'))
TIMESTAMP SYSDATE,'YYYYMMDD',
SOFT_DELETION CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED','ENABLE'))
);

CREATE TABLE USERS_DEPOSITS(
ID NUMBER NOT NULL GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
USER_ID NUMBER,
DEPOSIT_ID NUMBER,
USER_BANK_ID
SOFT_DELETION CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED','ENABLE'))
),

CREATE TABLE SECURITY_DOCUMENTS(
ID NUMBER GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
SECURITY_NAME varchar2(50),
SECURITY_DOCUMENT_TYPE varchar2(50),
FILE_SIZE varchar2(50),
FILE_EXTENSION varchar2(50),
FILE_URL varchar2(50),
SOFT_DELETION CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED' 'ENABLE'))
);

CREATE TABLE PAYMENTS RESTRICTIONS(
ID NUMBER GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
PAYMENT_LOWER_LIMIT
PAYMENT_UPPER_LIMIT
SOFT_DELETION CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED' 'ENABLE'))
);

CREATE TABLE PAYMENT_METHODS
ID NUMBER GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
PAYMENT_NAME varchar2(50),
PAYMENT_RESTRICTION_ID NUMBER,
SOFT_DELETION CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED' 'ENABLE'))
);

CREATE TABLE BANKS(
ID NUMBER GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
BANK_NAME varchar2(50),
SOFT_DELETION CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED' 'ENABLE'))
);

CREATE TABLE USER_BANK_ACCOUNTS(
ID NUMBER NOT NULL GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
USER_ID NUMBER,
BANK_ID NUMBER,
ACCOUNT_NUMBER  varchar2(255),
SOFT_DELETION CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED','ENABLE'))
);

CREATE TABLE USER_SECURITY_DOCUMENTS(
ID NUMBER GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
USER_ID NUMBER,
SECURITY_DOCUMENT_ID NUMBER,
SOFT_DELETION CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED' 'ENABLE'))
);

CREATE TABLE WITHDRAWAL(
ID NUMBER NOT NULL GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
WITHDRAWAL_AMOUNT varchar2(255),
USER_BANK_ACCOUNT_ID NUMBER,
WITHDRAWAL_REQUIREMENTS varchar2(255),
USER_SECURITY_DOCUMENT_ID NUMBER,
TIME_TIMESTAMP TIMESTAMP
STATUS CONSTRAINT CODE_STATE CHECK (STATUS IN ('SIN RETIRAR', 'RETIRADO'))
SOFT_DELETION CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED','ENABLE'))
);




CREATE TABLE BET_AUDITING_TABLE(
ID NUMBER NOT NULL GENERATED ALWAYS AS IDENTITY, PRIMARY KEY,
DATE_TIME TIMESTAMP,
TABLE
RECORD_ID
ACTION
USER_ID NUMBER,
IP varchar2(20),
SOFT_DELETION CONSTRAINT DELETIONS CHECK (SOFT_DELETION IN ('DELETED','ENABLE'))
);